View4D(twobyte2double(vol, hdr.quant_dynamic),[],...
	'PixelDimensions',[hdr.pix_mm_xy hdr.pix_mm_xy hdr.pix_mm_z],...
	'Time', frameTimes2mst(hdr.frame_len, hdr.frame_start)/60/1000,...
	'TimeUnits', 'min',...
	'FigureName',[hdr.patient_name ' - ' hdr.study]);